location_areas = [
    ("Canalave City","", None),
    ("Eterna City","", None),
    ("Pastoria City","", None),
    ("Sunyshore City","", None),
    ("Pokemon League","", None),
    ("Oreburgh Mine", "1F", 'cave'),
    ("Oreburgh Mine", "B1F", 'cave'),
    ("Valley Windworks","", 'grass'),
    ("Eterna Forest","", 'grass'),
    ("Fuego Ironworks","", 'grass'),
    ("Mt. Coronet", "Route 207", 'cave'),
    ("Mt. Coronet", "2F", 'cave'),
    ("Mt. Coronet", "3F", 'cave'),
    ("Mt. Coronet", "snowfall", 'grass'),
    ("Mt. Coronet", "blizzard", 'grass'),
    ("Mt. Coronet", "4F", 'cave'),
    ("Mt. Coronet", "5F", 'cave'),
    ("Mt. Coronet", "6F", 'cave'),
    ("Mt. Coronet", "7F", 'cave'),
    ("Mt. Coronet", "cave", 'cave'),
    ("Mt. Coronet", "Route 216", 'cave'),
    ("Mt. Coronet", "Route 211", 'cave'),
    ("Mt. Coronet", "B1F", 'cave'),
    ("Great Marsh", "Area 1", 'marsh'),
    ("Great Marsh", "Area 2", 'marsh'),
    ("Great Marsh", "Area 3", 'marsh'),
    ("Great Marsh", "Area 4", 'marsh'),
    ("Great Marsh", "Area 5", 'marsh'),
    ("Great Marsh", "Area 6", 'marsh'),
    ("Solaceon Ruins", "2F", 'floor'),
    ("Solaceon Ruins", "1F", 'floor'),
    ("Solaceon Ruins", "B1F a", 'floor'),
    ("Solaceon Ruins", "B1F b", 'floor'),
    ("Solaceon Ruins", "B1F c", 'floor'),
    ("Solaceon Ruins", "B2F a", 'floor'),
    ("Solaceon Ruins", "B2F b", 'floor'),
    ("Solaceon Ruins", "B2F c", 'floor'),
    ("Solaceon Ruins", "B3F a", 'floor'),
    ("Solaceon Ruins", "B3F b", 'floor'),
    ("Solaceon Ruins", "B3F c", 'floor'),
    ("Solaceon Ruins", "B3F d", 'floor'),
    ("Solaceon Ruins", "B3F e", 'floor'),
    ("Solaceon Ruins", "B4F a", 'floor'),
    ("Solaceon Ruins", "B4F b", 'floor'),
    ("Solaceon Ruins", "B4F c", 'floor'),
    ("Solaceon Ruins", "B4F d", 'floor'),
    ("Solaceon Ruins", "B5F", 'floor'),
    ("Victory Road", "1F", 'cave'),
    ("Victory Road", "2F", 'cave'),
    ("Victory Road", "B1F", 'cave'),
    ("Victory Road", "inside B1F", 'cave'),
    ("Victory Road", "inside", 'cave'),
    ("Victory Road", "inside exit", 'cave'),
    ("Ravaged Path","", 'cave'),
    ("Oreburgh Tunnel", "1F", 'cave'),
    ("Oreburgh Tunnel", "B1F", 'cave'),
    ("Stark Mountain","", 'grass'),
    ("Stark Mountain", "entrance", 'cave'),
    ("Stark Mountain", "inside", 'cave'),
    ("Spring Path","", 'grass'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 1", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 2 (alternate)", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 3", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Turnback Cave", "up to Pillar 2", 'cave'),
    ("Snowpoint Temple", "1F", 'cave'),
    ("Snowpoint Temple", "B1F", 'cave'),
    ("Snowpoint Temple", "B2F", 'cave'),
    ("Snowpoint Temple", "B3F", 'cave'),
    ("Snowpoint Temple", "B4F", 'cave'),
    ("Snowpoint Temple", "B5F", 'cave'),
    ("Wayward Cave", "1F", 'cave'),
    ("Wayward Cave", "B1F", 'cave'),
    ("Ruins Maniac Tunnel", "0-9 different Unown seen", 'cave'),
    ("Ruins Maniac Tunnel", "10-25 different Unown seen", 'cave'),
    ("Ruins Maniac Tunnel", "26+ different Unown seen", 'cave'),
    ("Trophy Garden","", 'grass'),
    ("Iron Island","", 'cave'),
    ("Iron Island", "1F", 'cave'),
    ("Iron Island", "B1F left", 'cave'),
    ("Iron Island", "B1F right", 'cave'),
    ("Iron Island", "B2F right", 'cave'),
    ("Iron Island", "B2F left", 'cave'),
    ("Iron Island", "B3F", 'cave'),
    ("Old Chateau", "", 'floor'), #entrance
    ("Old Chateau", "", 'floor'), # dining room
    ("Old Chateau", "", 'floor'), # 2F private room
    ("Old Chateau", "", 'floor'), # 2F
    ("Old Chateau", "", 'floor'), #2F leftmost room
    ("Old Chateau", "2F room with TV", 'floor'), # 2F left room
    ("Old Chateau", "", 'floor'), # 2F middle room
    ("Old Chateau", "2F room with eyes", 'floor'), # 2F right room
    ("Old Chateau", "", 'floor'), # 2F rightmost room
    ("Lake Verity", "before Galactic intervention", 'grass'),
    ("Lake Verity", "after Galactic intervention", 'grass'),
    ("Lake Valor","", 'grass'),
    ("Lake Acuity","", 'grass'),
    ("Valor Lakefront","", 'grass'),
    ("Acuity Lakefront","", 'grass'),
    ("Route 201","", 'grass'),
    ("Route 202","", 'grass'),
    ("Route 203","", 'grass'),
    ("Route 204", "south, towards Jubilife City", 'grass'),
    ("Route 204", "north, towards Floaroma City", 'grass'),
    ("Route 205", "south, towards Floaroma City", 'grass'),
    ("Route 205", "east, towards Eterna City", 'grass'),
    ("Route 206","", 'grass'),
    ("Route 207","", 'grass'),
    ("Route 208","", 'grass'),
    ("Route 209","", 'grass'),
    ("Lost Tower", "1F", 'floor'),
    ("Lost Tower", "2F", 'floor'),
    ("Lost Tower", "3F", 'floor'),
    ("Lost Tower", "4F", 'floor'),
    ("Lost Tower", "5F", 'floor'),
    ("Route 210", "south, towards Solaceon Town", 'grass'),
    ("Route 210", "west, towards Celestic Town", 'grass'),
    ("Route 211", "west, towards Eterna City", 'grass'),
    ("Route 211", "east, towards Celestic Town", 'grass'),
    ("Route 212", "north, towards Hearthome City", 'grass'),
    ("Route 212", "east, towards Pastoria City", 'grass'),
    ("Route 213","", 'grass'),
    ("Route 214","", 'grass'),
    ("Route 215","", 'grass'),
    ("Route 216","", 'grass'),
    ("Route 217","", 'grass'),
    ("Route 218","", 'grass'),
    ("Route 219","", 'grass'),
    ("Route 221","", 'grass'),
    ("Route 222","", 'grass'),
    ("Route 224","", 'grass'),
    ("Route 225","", 'grass'),
    ("Route 227","", 'grass'),
    ("Route 228","", 'grass'),
    ("Route 229","", 'grass'),
    ("Twinleaf Town","", None),
    ("Celestic City","", None),
    ("Resort Area","", None),
    ("Route 220","", None),
    ("Route 223","", None),
    ("Route 226","", None),
    ("Route 230","", None),
]

import csv
with open("dp-locations.csv", "wb") as f:
    writer = csv.writer(f)
    writer.writerow(('id', 'location', 'area', 'terrain'))
    for i, row in enumerate(location_areas):
        writer.writerow((i,) + row)

