mapNamesVersions = {
    'emerald': {
        0: {
            0: "Petalburg City",
            1: "Slateport City",
            5: "Lilycove City",
            6: "Mossdeep City",
            7: "Sootopolis City",
            8: "Ever Grande City",
            11: "Dewford Town",
            15: "Pacifidlog Town",
            16: "Route 101",
            17: "Route 102",
            18: "Route 103",
            19: "Route 104",
            20: "Route 105",
            21: "Route 106",
            22: "Route 107",
            23: "Route 108",
            24: "Route 109",
            25: "Route 110",
            26: "Route 111",
            27: "Route 112",
            28: "Route 113",
            29: "Route 114",
            30: "Route 115",
            31: "Route 116",
            32: "Route 117",
            33: "Route 118",
            34: "Route 119",
            35: "Route 120",
            36: "Route 121",
            37: "Route 122",
            38: "Route 123",
            39: "Route 124",
            40: "Route 125",
            41: "Route 126",
            42: "Route 127",
            43: "Route 128",
            44: "Route 129",
            45: "Route 130",
            46: "Route 131",
            47: "Route 132",
            48: "Route 133",
            49: "Route 134",
            50: "Route 124/underwater",
            51: "Route 126/underwater"},
        24: {
            0: "Meteor Falls",
            1: "Meteor Falls/back",
            2: "Meteor Falls/B1F",
            3: "Meteor Falls/back/small room",
            4: "Rusturf Tunnel",
            7: "Granite Cave/1F",
            8: "Granite Cave/B1F",
            9: "Granite Cave/B2F",
            10: "Granite Cave/1F/small Room",
            11: "Petalburg Woods",
            13: "Jagged Pass",
            14: "Fiery Pass",
            15: "Mt. Pyre/1F",
            16: "Mt. Pyre/2F",
            17: "Mt. Pyre/3F",
            18: "Mt. Pyre/4F",
            19: "Mt. Pyre/5F",
            20: "Mt. Pyre/6F",
            21: "Mt. Pyre/outside",
            22: "Mt. Pyre/summit",

            27: "Seafloor Cavern",
            28: "Seafloor Cavern",
            29: "Seafloor Cavern",
            30: "Seafloor Cavern",
            31: "Seafloor Cavern",
            32: "Seafloor Cavern",
            33: "Seafloor Cavern",
            34: "Seafloor Cavern",
            35: "Seafloor Cavern",

            37: "Cave of Origin/entrance",
            38: "Cave of Origin/1F",
            39: "Cave of Origin/B1F",
            40: "Cave of Origin/B2F",
            41: "Cave of Origin/B3F",
            43: "Victory Road/1F",
            44: "Victory Road/B1F",
            45: "Victory Road/B2F",
            46: "Shoal Cave",
            47: "Shoal Cave",
            48: "Shoal Cave",
            49: "Shoal Cave",
            52: "New Mauville/Entrance",
            53: "New Mauville",
            58: "Abondoned Ship",
            65: "Abondoned Ship",
            79: "Sky Pillar/1F",
            81: "Sky Pillar/3F",
            83: "Shoal Cave/B1F",
            84: "Sky Pillar/5F",
            86: "Magma Hideout",
            87: "Magma Hideout",
            88: "Magma Hideout",
            89: "Magma Hideout",
            90: "Magma Hideout",
            91: "Magma Hideout",
            92: "Magma Hideout",
            93: "Magma Hideout",
            94: "Mirage Tower",
            95: "Mirage Tower",
            96: "Mirage Tower",
            97: "Mirage Tower",
            98: "Desert Underpass",
            99: "Artisan Cave",
            100: "Artisan Cave",
            106: "Altering Cave", 
            107: "Meteor Falls"},
        26: {
            0: "Safari Zone/NW/mach bike area",
            1: "Safari Zone/NE/acro bike area",
            2: "Safari Zone/SW",
            3: "Safari Zone/SE",
            12: "Safari Zone/expansion north",
            13: "Safari Zone/expansion south"}},
    'firered': {
        1: {
            0: "Viridian Forest",
            1: "Mount Moon/1F",
            2: "Mount Moon/B1F",
            3: "Mount Moon/B2F",
            4: "S.S. Anne",
            37: "DIGLETT's Cave",
            39: "Victory Road/1F",
            40: "Victory Road/2F",
            41: "Victory Road/3F",
            59: u"Pok\xe9mon Mansion",
            60: u"Pok\xe9mon Mansion",
            61: u"Pok\xe9mon Mansion",
            62: u"Pok\xe9mon Mansion/B1F",
            63: "Safari Zone/center",
            64: "Safari Zone/right, area 1",
            65: "Safari Zone/top, area 2",
            66: "Safari Zone/left, area 3",
            72: "Cerulean Cave/1F",
            73: "Cerulean Cave/2F",
            74: "Cerulean Cave/B1F",
            81: "Rock Tunnel/1F",
            82: "Rock Tunnel/B1F",
            83: "Seafoam Islands/1F",
            84: "Seafoam Islands/B1F",
            85: "Seafoam Islands/B2F",
            86: "Seafoam Islands/B3F",
            87: "Seafoam Islands/B4F",
            90: u"Pok\xe9mon Tower/3F",
            91: u"Pok\xe9mon Tower/4F",
            92: u"Pok\xe9mon Tower/5F",
            93: u"Pok\xe9mon Tower/6F",
            94: u"Pok\xe9mon Tower/7F",
            95: "Power Plant",
            97: "Mt. Ember",
            98: "Mt. Ember/cave",
            99: "Mt. Ember/inside",
            100: "Mt. Ember/cave",
            103: "Mt. Ember/1F, cave behind team rocket",
            104: "Mt. Ember/B1F",
            105: "Mt. Ember/B2F",
            106: "Mt. Ember/B3F",
            107: "Mt. Ember/B2F",
            108: "Mt. Ember/B1F",
            109: "Berry Forest",
            110: "Icefall Cave/entrance",
            111: "Icefall Cave/1F",
            112: "Icefall Cave/B1F",
            113: "Icefall Cave/waterfall",
            121: "Patern Bush",
            122: "Altering Cave"},
        2: {  
            13: "Lost Cave/room 1",
            14: "Lost Cave/room 2",
            15: "Lost Cave/room 3",
            16: "Lost Cave/room 4",
            17: "Lost Cave/room 5",
            18: "Lost Cave/room 6",
            19: "Lost Cave/room 7",
            20: "Lost Cave/room 8",
            21: "Lost Cave/room 9",
            22: "Lost Cave/room 10",
            23: "Lost Cave/item rooms",
            24: "Lost Cave/item rooms",
            25: "Lost Cave/item rooms",
            26: "Lost Cave/item rooms",
            27: "Monean Chamber",
            28: "Liptoo Chamber",
            29: "Weepth Chamber",
            30: "Dilford Chamber",
            31: "Scufib Chamber",
            32: "Rixy Chamber",
            33: "Viapos Chamber"},
        3: {
            0: "Pallet Town",
            1: "Viridian City",
            3: "Cerulean City",
            5: "Vermillion City",
            6: "Celadon City",
            7: "Fuchsia City",
            8: "Cinnabar Island",
            12: "One Island",
            15: "Four Island",
            16: "Five Island",
            19: "Route 1",
            20: "Route 2",
            21: "Route 3",
            22: "Route 4",
            23: "Route 5",
            24: "Route 6",
            25: "Route 7",
            26: "Route 8",
            27: "Route 9",
            28: "Route 10",
            29: "Route 11",
            30: "Route 12",
            31: "Route 13",
            32: "Route 14",
            33: "Route 15",
            34: "Route 16",
            35: "Route 17",
            36: "Route 18",
            37: "Route 19",
            38: "Route 20",
            39: "Route 21",
            40: "Route 21",
            41: "Route 22",
            42: "Route 23",
            43: "Route 24",
            44: "Route 25",
            45: "Kindle Road",
            46: "Treasure Beach",
            47: "Cape Brink",
            48: "Bond Bridge",
            49: "Three Isle Port",
            54: "Resort Gorgeous",
            55: "Water Labyrinth",
            56: "Five Isle Meadow",
            57: "Memorial Pillar",
            58: "Outcast Island",
            59: "Green Path",
            60: "Water Path",
            61: "Ruin Valley",
            62: "Trainer Tower",
            63: "Canyon Entrance",
            64: "Sevault Canyon",
            65: "Tanoby Ruins"}},
}

import csv

def something(filename, names):
    with open(filename, 'wb') as f:
        writer = csv.writer(f)
        writer.writerow('bank num location area'.split())
        for bank in sorted(names):
            for num in sorted(names[bank]):
                name = names[bank][num]
                location, _, area = name.partition("/")
                writer.writerow((bank, num,
                                 location.encode('utf-8'),
                                 area.encode('utf-8')))

something('rse-locations.csv', mapNamesVersions['emerald'])
something('frlg-locations.csv', mapNamesVersions['firered'])
