location_areas = [
    (66, 'Blackthorn City', '', None),
    (29, 'Burned Tower', '1F', 'floor'),
    (30, 'Burned Tower', 'B1F', 'floor'),
    (100, 'Celadon City', '', None),
    (98, 'Cerulean City', '', None),
    (3, 'Cherrygrove City', '', None),
    (52, 'Cianwood City', '', None),
    (96, 'Cinnabar Island', '', None),
    (71, 'Dark Cave', 'Blackthorn City entrance', 'cave'),
    (70, 'Dark Cave', 'Violet City entrance', 'cave'),
    (134, 'Diglett\'s Cave', '', 'cave'),
    (67, 'Dragon\'s Den', '', None),
    (28, 'Ecruteak City', '', None),
    (101, 'Fuchsia City', '', None),
    (61, 'Ice Cave', '1F', 'cave'),
    (62, 'Ice Cave', 'B1F', 'cave'),
    (63, 'Ice Cave', 'B2F', 'cave'),
    (64, 'Ice Cave', 'B3F', 'cave'),
    (21, 'Ilex Forest', '', 'grass'),
    (59, 'Lake of Rage', '', None),
    (107, 'Mt. Moon', '1F', 'cave'),
    (108, 'Mt. Moon', '2F', 'cave'),
    (73, 'Mt. Moon', 'outside', None),
    (54, 'Mt. Mortar', '1F', 'cave'),
    (57, 'Mt. Mortar', 'B1F', 'cave'),
    (55, 'Mt. Mortar', 'Lower Cave', 'cave'),
    (56, 'Mt. Mortar', 'Upper Cave', 'cave'),
    (81, 'Mt. Silver', '1F top', 'grass'),
    (80, 'Mt. Silver', '1F', 'cave'),
    (87, 'Mt. Silver', '2F', 'cave'),
    (89, 'Mt. Silver', '3F', 'cave'),
    (82, 'Mt. Silver', '4F', 'cave'),
    (88, 'Mt. Silver', 'mountainside', 'grass'),
    (86, 'Mt. Silver', 'outside', 'grass'),
    (90, 'Mt. Silver', 'top', 'grass'),
    (24, 'National Park', '', 'grass'),
    (1, 'New Bark Town', '', None),
    (41, 'Olivine City', '', None),
    (102, 'Pallet Town', '', None),
    (109, 'Rock Tunnel', '1F', 'cave'),
    (110, 'Rock Tunnel', 'B1F', 'cave'),
    (112, 'Route 1', '', 'grass'),
    (113, 'Route 2', '', 'grass'),
    (137, 'Route 2', 'something else', 'grass'),
    (114, 'Route 3', '', 'grass'),
    (115, 'Route 4', '', 'grass'),
    (116, 'Route 5', '', 'grass'),
    (117, 'Route 6', '', 'grass'),
    (118, 'Route 7', '', 'grass'),
    (119, 'Route 8', '', 'grass'),
    (120, 'Route 9', '', 'grass'),
    (121, 'Route 10', '', 'grass'),
    (122, 'Route 11', '', 'grass'),
    (93, 'Route 12', '', 'grass'),
    (123, 'Route 13', '', 'grass'),
    (124, 'Route 14', '', 'grass'),
    (125, 'Route 15', '', 'grass'),
    (126, 'Route 16', '', 'grass'),
    (127, 'Route 17', '', 'grass'),
    (128, 'Route 18', '', 'grass'),
    (94, 'Route 19', '', None),
    (95, 'Route 20', '', None),
    (129, 'Route 21', '', 'grass'),
    (130, 'Route 22', '', 'grass'),
    (131, 'Route 24', '', 'grass'),
    (132, 'Route 25', '', 'grass'),
    (104, 'Route 26', '', 'grass'),
    (105, 'Route 27', '', 'grass'),
    (106, 'Route 28', '', 'grass'),
    (2, 'Route 29', '', 'grass'),
    (4, 'Route 30', '', 'grass'),
    (5, 'Route 31', '', 'grass'),
    (9, 'Route 32', '', 'grass'),
    (18, 'Route 33', '', 'grass'),
    (22, 'Route 34', '', 'grass'),
    (23, 'Route 35', '', 'grass'),
    (26, 'Route 36', '', 'grass'),
    (27, 'Route 37', '', 'grass'),
    (39, 'Route 38', '', 'grass'),
    (40, 'Route 39', '', 'grass'),
    (42, 'Route 40', '', 'grass'),
    (43, 'Route 41', '', 'grass'),
    (53, 'Route 42', '', 'grass'),
    (58, 'Route 43', '', 'grass'),
    (60, 'Route 44', '', 'grass'),
    (68, 'Route 45', '', 'grass'),
    (69, 'Route 46', '', 'grass'),
    (72, 'Route 47', '', 'grass'),
    (83, 'Route 47', 'cave gate', None),
    (84, 'Route 47', 'inside cave', 'cave'),
    (103, 'Route 48', '', 'grass'),
    (11, 'Ruins of Alph', 'Interior A', 'floor'),
    (12, 'Ruins of Alph', 'Interior B', 'floor'),
    (13, 'Ruins of Alph', 'Interior C', 'floor'),
    (14, 'Ruins of Alph', 'Interior D', 'floor'),
    (10, 'Ruins of Alph', 'Outside', 'grass'),
    (75, 'Seafoam Islands', '1F', 'cave'),
    (76, 'Seafoam Islands', 'B1F', 'cave'),
    (77, 'Seafoam Islands', 'B2F', 'cave'),
    (78, 'Seafoam Islands', 'B3F', 'cave'),
    (79, 'Seafoam Islands', 'B4F', 'cave'),
    (19, 'Slowpoke Well', '1F', 'cave'),
    (20, 'Slowpoke Well', 'B1F', 'cave'),
    (7, 'Sprout Tower', '2F', 'floor'),
    (8, 'Sprout Tower', '3F', 'floor'),
    (31, 'Tin Tower', '2F', 'floor'),
    (32, 'Tin Tower', '3F', 'floor'),
    (33, 'Tin Tower', '4F', 'floor'),
    (34, 'Tin Tower', '5F', 'floor'),
    (35, 'Tin Tower', '6F', 'floor'),
    (36, 'Tin Tower', '7F', 'floor'),
    (37, 'Tin Tower', '8F', 'floor'),
    (38, 'Tin Tower', '9F', 'floor'),
    (85, 'Tin Tower', '10F', 'floor'),
    (133, 'Tohjo Falls', '', 'cave'),
    (15, 'Union Cave', '1F', 'cave'),
    (16, 'Union Cave', 'B1F', 'cave'),
    (17, 'Union Cave', 'B2F', 'cave'),
    (139, 'Unknown 138', '', None),
    (50, 'Unknown 49', '', None),
    (51, 'Unknown 50', '', None),
    (65, 'Unknown 64', '', None),
    (91, 'Unknown 90', '', None),
    (140, 'Unknown Dungeon', '1F', 'cave'),
    (141, 'Unknown Dungeon', '2F', 'cave'),
    (142, 'Unknown Dungeon', 'B1F', 'cave'),
    (74, 'Unknown; all Poliwag', '', None),
    (92, 'Unknown; all Rattata', '', None),
    (25, 'Unknown; all bugs', '', None),
    (99, 'Vermilion City', '', None),
    (111, 'Victory Road', '', 'cave'),
    (135, 'Victory Road', 'one', 'cave'),
    (136, 'Victory Road', 'two', 'cave'),
    (6, 'Violet City', '', None),
    (97, 'Viridian City', '', None),
    (138, 'Viridian Forest', '', 'grass'),
    (49, 'Whirl Islands', 'B3F', 'cave'),
    (46, 'Whirl Islands', 'empty floor X', 'cave'),
    (48, 'Whirl Islands', 'empty floor Y', 'cave'),
    (44, 'Whirl Islands', 'unknown floors A', 'cave'),
    (45, 'Whirl Islands', 'unknown floors B', 'cave'),
    (47, 'Whirl Islands', 'unknown floors C', 'cave'),
]

import csv
with open("hgss-locations.csv", "wb") as f:
    writer = csv.writer(f)
    writer.writerow(('id', 'location', 'area', 'terrain'))
    for row in location_areas:
        writer.writerow(row)
